[package]
authors = ["Yohai Berreby (yberreby) <yohaiberreby@gmail.com>"]
license = "MIT OR Apache-2.0"
name = "rulis"
version = "0.1.0"

[dependencies]
env_logger = "0.3.5"
log = "0.3.6"
num = "0.1.35"
rustyline = "1.0.0"
stacker = "0.1.2"
